/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'studentId' : bigint,
  'present' : boolean,
  'date' : string,
}
export interface Mark {
  'studentId' : bigint,
  'subject' : string,
  'score' : bigint,
  'examType' : string,
}
export interface Student {
  'id' : bigint,
  'contact' : string,
  'name' : string,
  'grade' : string,
  'rollNumber' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'staff' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMark' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'addStudent' : ActorMethod<[string, string, string, string], bigint>,
  'addSubject' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'authenticate' : ActorMethod<[string, string], string>,
  'editSubject' : ActorMethod<[string, string], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<string>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByStudent' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMarksByStudent' : ActorMethod<[bigint], Array<Mark>>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getUserByToken' : ActorMethod<
    [string],
    [] | [{ 'username' : string, 'name' : string, 'role' : UserRole }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logout' : ActorMethod<[string], undefined>,
  'recordAttendance' : ActorMethod<[bigint, string, boolean], undefined>,
  'registerUser' : ActorMethod<[string, string, UserRole, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyToken' : ActorMethod<[string], [] | [Principal]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];